### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'shape' " when use "patch" mode config.

### ISSUE THREAD

**Issue by andreasalamanos** [liweitianux/fg21sim#4]
When use the "patch" mode,
 returns error:
"...
self.ysize_in, self.xsize_in = self.data.shape
AttributeError: 'NoneType' object has no attribute 'shape'  "  

Also, the get-healpix-patch returns an unreadable file.

**Comment by liweitianux** [comment]
Hi @rasputin1917 , thanks for trying this software.

I think you were loading an invalid FITS image to `sky.py`, so the `self.data` was `None`, which should be a Numpy array representing the image.  A FITS image stores the data in its primary extension, which is loaded by `sky.py`, while a FITS spectrum usually leaves the primary extension empty.  Please make sure you're using a valid FITS image.

The `get-healpix-patch` extracts a sky patch from an all-sky HEALPix map, e.g.,
```
get-healpix-patch --smooth --center 0,-27 --size 1800,1800 --pixelsize 20 \
    haslam408_dsds_Remazeilles2014_ns512.fits \
    haslam408-eor0-fov10.fits
```
The input file [`haslam408_dsds_Remazeilles2014_ns512.fits`](https://github.com/liweitianux/fg21sim/blob/master/data/haslam408_dsds_Remazeilles2014_ns512.fits.xz) is an all-sky HEALPix map.  The output file `haslam408-eor0-fov10.fits` is a plain FITS image and can be viewed with `ds9`.

Cheers

**Comment by andreasalamanos** [comment]
Hi! Thanks for th

> Hi @rasputin1917 , thanks for trying this software.
> 
> I think you were loading an invalid FITS image to `sky.py`, so the `self.data` was `None`, which should be a Numpy array representing the image. A FITS image stores the data in its primary extension, which is loaded by `sky.py`, while a FITS spectrum usually leaves the primary extension empty. Please make sure you're using a valid FITS image.
> 
> The `get-healpix-patch` extracts a sky patch from an all-sky HEALPix map, e.g.,
> 
> ```
> get-healpix-patch --smooth --center 0,-27 --size 1800,1800 --pixelsize 20 \
>     haslam408_dsds_Remazeilles2014_ns512.fits \
>     haslam408-eor0-fov10.fits
> ```

Hi @rasputin1917 , thanks for trying this software.

I think you were loading an invalid FITS image to sky.py, so the self.data was None, which should be a Numpy array representing the image. A FITS image stores the data in its primary extension, which is loaded by sky.py, while a FITS spectrum usually leaves the primary extension empty. Please make sure you're using a valid FITS image.

The get-healpix-patch extracts a sky patch from an all-sky HEALPix map, e.g.,

get-healpix-patch --smooth --center 0,-27 --size 1800,1800 --pixelsize 20 \
    haslam408_dsds_Remazeilles2014_ns512.fits \
    haslam408-eor0-fov10.fits

The input file haslam408_dsds_Remazeilles2014_ns512.fits is an all-sky HEALPix map. The output file haslam408-eor0-fov10.fits is a plain FITS image and can be viewed with ds9.

Cheers

> 
> The input file [`haslam408_dsds_Remazeilles2014_ns512.fits`](https://github.com/liweitianux/fg21sim/blob/master/data/haslam408_dsds_Remazeilles2014_ns512.fits.xz) is an all-sky HEALPix map. The output file `haslam408-eor0-fov10.fits` is a plain FITS image and can be viewed with `ds9`.
> 
> Cheers

Hi! thanks for the immediate reply. 
Concerning the FITS file, if it was invalid, "healpix" mode config. wouldn't work too, right? But now it seems that it is working. However when I use the "heaplix" mode for "foregrounds", I get a sky map that is almost the same with Haslam 408 map, with almost no differences. 

I checked the Haslam and foreground maps, with the "Aladin package" and they both work for sure
Here is the configuration I use for getting foregrounds for both "healpix" and "patch" modes:

```
[foregrounds]

galactic/synchrotron =True

galactic/freefree = 
galactic/snr = False
extragalactic/clusters = False

[sky]

type = "patch"
  
  [[patch]]
 
  xcenter = 0.0
  ycenter = -27.0

  xsize = 1000
  ysize = 1000

    pixelsize = 10.0
  
  [[healpix]]
    nside = 1024

[frequency]

type = "calc"

start = 400.0
stop = 800.0
step = 25.0

[output]
filename_pattern = "andreas_{frequency:06.2f}.fits"

float32 = True
checksum = True

clobber = True

manifest = "/home/andreas/Desktop/manifest"
[cosmology]
# Hubble constant at z=0; [km/s/Mpc]
H0 = 71.0
# Density of non-relativistic matter in units of the critical density at z=0
OmegaM0 = 0.27
# Density of the baryon at present day
Omegab0 = 0.046
# Present-day CMB temperature; [K]
Tcmb0 = 2.75
# Present-day rms density fluctuations on a scale of 8 h^-1 [Mpc]
sigma8 = 0.81
# Scalar spectral index
ns = 0.96


# Configurations for initialization/reconfiguration of the `logging` module
[logging]
level = "info"

format ="%(asctime)s [%(levelname)s] <%(name)s:%(lineno)d> %(message)s"
datefmt = "%H:%M:%S"

filename = ""

stream = "stderr"
#
# Galactic emission components

[galactic]
  [[synchrotron]]
  # The template map for the simulation, e.g., Haslam 408 MHz survey.

  template = "/home/andreas/fg21sim/data/haslam408_dsds_Remazeilles2014_ns512.fits"
   template_freq = 408.0

  # Spectral index map
  indexmap = "/home/andreas/fg21sim/data/synchrotron_specind2_ns512.fits"
  add_smallscales = False
  
  lmin = 10
  lmax = 3071
  prefix = "synchro"
  # Output directory to save the simulated results
  output_dir =None 
```

Thanks for your time again

Ps. I suppose that "patch" config returns a patch of haslam map infected with foreground, right?

**Comment by liweitianux** [comment]
On Tue, 27 Nov 2018 09:11:22 +0000 (UTC)
rasputin1917 <notifications@github.com> wrote:

> Concerning the FITS file, if it was invalid, "healpix" mode config.
> wouldn't work too, right? But now it seems that it is working.

The HEALPix image is a FITS table file, i.e., not a FITS image file. e.g.,

$ fitsinfo haslam408_dsds_Remazeilles2014_ns512.fits   
Filename: haslam408_dsds_Remazeilles2014_ns512.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       7   ()      
  1                1 BinTableHDU     42   3072R x 1C   [1024E]

(`fitsinfo` is a CLI tool from `astropy` package)

The `fg21sim` software doesn't auto extract the patch from the all-sky
HEALPix map, so I wrote the `get-healpix-patch` to do it.  If you want to
simulate the foreground in a patch of the sky, you need first to use the
`get-healpix-patch` to extract the patch from the templates, and tell
`fg21sim` to use the extracted patches (in the config file).

Sorry for the lack of documents.

> However when I use the "heaplix" mode for "foregrounds", I get a sky map
> that is almost the same with Haslam 408 map, with almost no differences. 

Yes, the Galactic synchrotron foreground at a different frequency is
simulated by extrapolating from the Haslam 408 MHz template.

> Ps. I suppose that "patch" config returns a patch of haslam map infected
> with foreground, right?

No. This software simulates multiple foreground component separately.  It
actually focus on implementing a better method (more physically motivated) to
simulate the low-frequency images of radio halos.  However, this part is
undergoing major revision, so the simulation of `extragalactic/clusters` may
not work at the moment.  I have a paper in which the simulation details of
radio halos are described, but it's still under revision.

On simulating a patch of sky with this software, I have a basic guide at:
https://github.com/liweitianux/cdae-eor/blob/master/doc/data.md

Hope it helps.


Cheers,
-- 
Aaron

**Comment by andreasalamanos** [comment]
Thanks again!
