### ISSUE TITLE
Error generating FITS using asymmetric lightcone box 

### ISSUE THREAD

**Issue by parphyam** [liweitianux/fg21sim#5]
Hi,
I am trying to convert a HI signal binary into FITS using `21cmfast_lightcone.py`. Since the cube is asymmetric (dimension [232,232,339]), the 3rd axis being the LoS axis. I added an extra line `self.Dc_z = cosmo.comoving_distance(zmax).value - cosmo.comoving_distance(zmin).value`  and 
`def dDc_z(self):
        return self.Dc_z /self.cube.shape[2]`. 
I have also modified w.wcs.cdelt as `w.wcs.cdelt = np.array([self.Dc_cell, self.Dc_cell, self.dDc_z])`. Now after finding the cube, when I'm trying to get slices using `get_slice_zfreq.py`, I am getting the redshifts till 9.944. However, this is followed by the following error :
`Traceback (most recent call last):
  File "get_slice_zfreq.py", line 144, in <module>
    main()
  File "get_slice_zfreq.py", line 139, in main
    data = lightcone.get_slice(z)
  File "get_slice_zfreq.py", line 68, in get_slice
    raise ValueError("requested redshift out of range: %.2f" % z)
ValueError: requested redshift out of range: 9.96
`
I am passing the z values for this code from a text file z.list using `-z $(cat z.txt)`. Can you let me know why such an error is arising?

**Comment by liweitianux** [comment]
@parphyam, thank you for interesting in my scripts. If you still have any questions, please open issues to me. Although I no longer use these scripts after my graduation in last year, I'll glad to provide help.
