### ISSUE TITLE
git lsf pull error

### ISSUE THREAD

**Issue by zhaotingchen** [liweitianux/fg21sim#6]
Hi,
I'm trying to download the template data, and ``git lsf pull`` gives me:
> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. Failed to fetch some objects from 'https://github.com/liweitianux/fg21sim.git/info/lfs'

I'm wondering if there is any other way to get the template data? I also tried the data manifest but an error message was returned:
> ValueError: Downloaded file has wrong size

Many thanks!

**Comment by liweitianux** [comment]
Hi.

Yes, unfortunately, my LFS quota was exceeded for unknown reasons :(

I've uploaded the data files at below:

http://www.liweitian.com/files/fg21sim/GalacticSNRs_Green2014.csv
http://www.liweitian.com/files/fg21sim/Halpha_fwhm06_ns1024.fits.xz
http://www.liweitian.com/files/fg21sim/SFD_i100_ns1024.fits.xz
http://www.liweitian.com/files/fg21sim/haslam408_dsds_Remazeilles2014_ns512.fits.xz
http://www.liweitian.com/files/fg21sim/synchrotron_specind2_ns512.fits.xz

I'll keep them at least til the end of this weekend.

Cheers.

**Comment by liweitianux** [comment]
I just found that the data can also be obtained from: https://gitee.com/shao-eor/fg21sim/tree/master/data

**Comment by zhaotingchen** [comment]
Thanks a lot! I've downloaded them from the link. I've also tried the gitee repo but it returns an error ``[404] Object not found``.

**Comment by Xiezhaotong** [comment]
Hi,
I used `git lsf pull` to download the template data, but also the problem that Mr. Chen encountered.
And I opened it on gitee and found an error `Not Found`.
What I want to ask you is there any other way to download this data?
Thanks, please.
