### ISSUE TITLE
git lfs pull error

### ISSUE THREAD

**Issue by Xiezhaotong** [liweitianux/fg21sim#7]
Hi,
I used `git lsf pull` to download the template data, but also the problem that Mr. Chen encountered.
And I opened it on gitee and found an error `Not Found`.
What I want to ask you is there any other way to download this data?
Thanks, please.

**Comment by ChenxiSSS** [comment]
Hi,

Thank you for reaching out. We will offer an alternative method to download the data soon. Also, this repo is considered obsolete. Future issues can be directed to https://github.com/Fg21Sim.

Best,
Chenxi

**Comment by Xiezhaotong** [comment]
Thanks for your message. I'm looking forward to getting the data you provided soon.

But I still found the problem that data cannot be `git lfs pull` at https://github.com/Fg21Sim. It returned:

`Error downloading object: data/Halpha_fwhm06_ns1024.fits.xz (85b9d1f): Smudge error: Error downloading data/Halpha_fwhm06_ns1024.fits.xz (85b9d1ffe75ca87ae2a8c0bf8d674a95d92b6bbff68caa301164aa46848f5984): [85b9d1ffe75ca87ae2a8c0bf8d674a95d92b6bbff68caa301164aa46848f5984] Object does not exist on the server: [404] Object does not exist on the server`.

**Comment by liweitianux** [comment]
Hi @Xiezhaotong , we'll put the data at another place and provide you with the download link later. Please hold on.

The Github LFS storage is really an issue. We'll resolve it in some way...

Cheers.

**Comment by ChenxiSSS** [comment]
We have addressed the issue at https://github.com/Fg21Sim/fg21sim/issues/2. This one should be closed.

**Comment by Xiezhaotong** [comment]
Thanks a million. I really appreciate it.
